#!/bin/sh /etc/rc.common
USE_PROCD=1
START=96
STOP=9

PROG=/usr/share/meow/arp-hijack.sh

start_service() {
	local enabled
	config_load meow
	config_get_bool enabled arp enabled 0
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance meow-arp
	procd_set_param command "$PROG" run
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "meow"
}
