include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-meow
PKG_VERSION:=0.21.2
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for meow (panel + settings)
LUCI_DEPENDS:=+luci-base +meow
LUCI_PKGARCH:=all

PKG_MAINTAINER:=Max Lv <max.c.lv@gmail.com>
PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
